global:
  scrape_interval: 5s

scrape_configs:
  - job_name: 'telco_model_metrics'
    static_configs:
      - targets: ['localhost:8000']
      
  - job_name: 'inference_exporter'
    static_configs:
      - targets: ['localhost:8002']