# -*- coding: utf-8 -*-
"""Modelling.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/12VbLsW6glkE7FlLHNaA0R9vYL_JPeYdK
"""

import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
import mlflow
import mlflow.sklearn

# === Autolog aktif ===
mlflow.autolog()

# === Load data ===
df = pd.read_csv("telco_preprocessing.csv")

# === Pisahkan fitur dan target ===
X = df.drop("Churn", axis=1)
y = df["Churn"]

# Gabungkan X dan y sementara untuk membersihkan baris NaN
df_model = pd.concat([X, y], axis=1)
df_model = df_model.dropna()

# Pisahkan kembali
X = df_model.drop("Churn", axis=1)
y = df_model["Churn"]

# === Encoding fitur kategorikal ===
X = pd.get_dummies(X)

# === Encoding target jika masih string ===
if y.dtype == "object":
    y = y.map({"No": 0, "Yes": 1})

# === Train-test split ===
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

# === MLflow Logging ===
with mlflow.start_run():
    model = RandomForestClassifier(random_state=42)
    model.fit(X_train, y_train)
    mlflow.sklearn.log_model(model, "model")

